# Data : we shall generate the or data

x1 x2 --> y
0  0  --> 0
0  1  --> 1
1  0  --> 1
1  1  --> 1

In [1]:
import numpy as np
num_input = 4

In [2]:
input_array = np.array([[0,0], [0,1], [1,0], [1,1]])
input_array

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [3]:
# output data -- OR function
output_array = np.array([0,1,1,1])
output_array

array([0, 1, 1, 1])

#Perceptron Model
##Importing libraries

In [4]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD

In [5]:
classifier = Sequential()
classifier.add(Dense(input_shape=(2,), units=1, activation='sigmoid'))
#bias term added by default
classifier.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 3         
                                                                 
Total params: 3 (12.00 Byte)
Trainable params: 3 (12.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [6]:
classifier.compile(optimizer=SGD(learning_rate=0.5), loss='binary_crossentropy', metrics=['accuracy'])

In [8]:
classifier.fit(input_array, output_array, epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 12ms/step - loss: 0.2903 - accuracy: 0.7500
Epoch 2/100
1/1 [==============================] - 0s 10ms/step - loss: 0.2869 - accuracy: 0.7500
Epoch 3/100
1/1 [==============================] - 0s 9ms/step - loss: 0.2835 - accuracy: 0.7500
Epoch 4/100
1/1 [==============================] - 0s 9ms/step - loss: 0.2802 - accuracy: 0.7500
Epoch 5/100
1/1 [==============================] - 0s 9ms/step - loss: 0.2769 - accuracy: 0.7500
Epoch 6/100
1/1 [==============================] - 0s 9ms/step - loss: 0.2738 - accuracy: 0.7500
Epoch 7/100
1/1 [==============================] - 0s 9ms/step - loss: 0.2707 - accuracy: 0.7500
Epoch 8/100
1/1 [==============================] - 0s 9ms/step - loss: 0.2676 - accuracy: 1.0000
Epoch 9/100
1/1 [==============================] - 0s 9ms/step - loss: 0.2646 - accuracy: 1.0000
Epoch 10/100
1/1 [==============================] - 0s 9ms/step - loss: 0.2617 - accuracy: 1.0000
Epoch 11/100
1/1 [=========

#Model Prediction and Validation

In [9]:
y_pred = classifier.predict(input_array)
y_pred = (y_pred > 0.5)
y_pred

1/1 [==============================] - 0s 68ms/step


array([[False],
       [ True],
       [ True],
       [ True]])

In [10]:
from sklearn.metrics import accuracy_score
print('accuracy', accuracy_score(y_pred, output_array))

accuracy 1.0


##We can see here after having few epochs the model accuracy became 100%

# Perceptron model for XOR data

x1 x2 --> y
0  0  --> 0
0  1  --> 1
1  0  --> 1
1  1  --> 0

In [11]:
input_array = np.array([[0,0], [0,1], [1,0], [1,1]])
input_array

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [12]:
# output data -- OR function
output_array = np.array([0,1,1,0])
output_array

array([0, 1, 1, 0])

In [13]:
classifier = Sequential()
classifier.add(Dense(input_shape=(2,), units=1, activation='sigmoid'))
#bias term added by default
classifier.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 3 (12.00 Byte)
Trainable params: 3 (12.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
classifier.compile(optimizer=SGD(learning_rate=0.5), loss='binary_crossentropy', metrics=['accuracy'])

In [15]:
classifier.fit(input_array, output_array, epochs=100)

Epoch 1/100
1/1 [==============================] - 1s 626ms/step - loss: 0.7351 - accuracy: 0.7500
Epoch 2/100
1/1 [==============================] - 0s 16ms/step - loss: 0.7323 - accuracy: 0.5000
Epoch 3/100
1/1 [==============================] - 0s 14ms/step - loss: 0.7297 - accuracy: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 15ms/step - loss: 0.7275 - accuracy: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 14ms/step - loss: 0.7253 - accuracy: 0.5000
Epoch 6/100
1/1 [==============================] - 0s 14ms/step - loss: 0.7234 - accuracy: 0.5000
Epoch 7/100
1/1 [==============================] - 0s 15ms/step - loss: 0.7216 - accuracy: 0.5000
Epoch 8/100
1/1 [==============================] - 0s 16ms/step - loss: 0.7199 - accuracy: 0.5000
Epoch 9/100
1/1 [==============================] - 0s 19ms/step - loss: 0.7183 - accuracy: 0.5000
Epoch 10/100
1/1 [==============================] - 0s 16ms/step - loss: 0.7168 - accuracy: 0.5000
Epoch 11/100
1/1 [

In [17]:
y_pred = classifier.predict(input_array)
y_pred = (y_pred > 0.5)
print('accuracy', accuracy_score(y_pred, output_array))

1/1 [==============================] - 0s 18ms/step
accuracy 0.5


In [18]:
##We can see here after having 100 epochs the model is not able to predict or give 100% accuracy.

#Multilevel Perceptron Model

In [19]:
input_array = np.array([[0,0], [0,1], [1,0], [1,1]])
input_array

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [20]:
# output data -- OR function
output_array = np.array([0,1,1,0])
output_array

array([0, 1, 1, 0])

In [21]:
classifier = Sequential()
classifier.add(Dense(input_shape=(2,), units=10, activation='relu'))
classifier.add(Dense(units=1, activation='sigmoid'))
#bias term added by default
classifier.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 10)                30        
                                                                 
 dense_3 (Dense)             (None, 1)                 11        
                                                                 
Total params: 41 (164.00 Byte)
Trainable params: 41 (164.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [22]:
classifier.compile(optimizer=SGD(learning_rate=0.5), loss='binary_crossentropy', metrics=['accuracy'])

In [23]:
classifier.fit(input_array, output_array, epochs=100)

Epoch 1/100
1/1 [==============================] - 1s 1s/step - loss: 0.6805 - accuracy: 0.5000
Epoch 2/100
1/1 [==============================] - 0s 25ms/step - loss: 0.6664 - accuracy: 0.5000
Epoch 3/100
1/1 [==============================] - 0s 22ms/step - loss: 0.6575 - accuracy: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 22ms/step - loss: 0.6498 - accuracy: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 22ms/step - loss: 0.6438 - accuracy: 0.5000
Epoch 6/100
1/1 [==============================] - 0s 17ms/step - loss: 0.6359 - accuracy: 0.7500
Epoch 7/100
1/1 [==============================] - 0s 15ms/step - loss: 0.6270 - accuracy: 0.7500
Epoch 8/100
1/1 [==============================] - 0s 16ms/step - loss: 0.6236 - accuracy: 0.7500
Epoch 9/100
1/1 [==============================] - 0s 25ms/step - loss: 0.6124 - accuracy: 0.7500
Epoch 10/100
1/1 [==============================] - 0s 13ms/step - loss: 0.6068 - accuracy: 0.7500
Epoch 11/100
1/1 [===

In [24]:
y_pred = classifier.predict(input_array)
y_pred = (y_pred > 0.5)
print('accuracy', accuracy_score(y_pred, output_array))

1/1 [==============================] - 0s 43ms/step
accuracy 1.0
